server.port: 8086
# database configuration postgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gymdb
spring.datasource.username=postgres
spring.datasource.password=bini2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
